# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qspect_v2.ui'
#
# Created: Tue Apr 26 15:54:58 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(718, 650)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_process = QtGui.QPushButton(self.tab)
        self.pushButton_process.setObjectName(_fromUtf8("pushButton_process"))
        self.gridLayout_2.addWidget(self.pushButton_process, 18, 0, 1, 2)
        self.lineEdit_InjDate = QtGui.QLineEdit(self.tab)
        self.lineEdit_InjDate.setObjectName(_fromUtf8("lineEdit_InjDate"))
        self.gridLayout_2.addWidget(self.lineEdit_InjDate, 16, 1, 1, 1)
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setMinimumSize(QtCore.QSize(350, 0))
        self.textBrowser.setBaseSize(QtCore.QSize(0, 0))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_2.addWidget(self.textBrowser, 0, 2, 28, 1)
        self.label_weight = QtGui.QLabel(self.tab)
        self.label_weight.setObjectName(_fromUtf8("label_weight"))
        self.gridLayout_2.addWidget(self.label_weight, 14, 0, 1, 1)
        self.label_n_tomos = QtGui.QLabel(self.tab)
        self.label_n_tomos.setObjectName(_fromUtf8("label_n_tomos"))
        self.gridLayout_2.addWidget(self.label_n_tomos, 6, 0, 1, 2)
        self.lineEdit_height = QtGui.QLineEdit(self.tab)
        self.lineEdit_height.setObjectName(_fromUtf8("lineEdit_height"))
        self.gridLayout_2.addWidget(self.lineEdit_height, 13, 1, 1, 1)
        self.label_n_slices = QtGui.QLabel(self.tab)
        self.label_n_slices.setObjectName(_fromUtf8("label_n_slices"))
        self.gridLayout_2.addWidget(self.label_n_slices, 7, 0, 1, 2)
        self.label_StepDur = QtGui.QLabel(self.tab)
        self.label_StepDur.setObjectName(_fromUtf8("label_StepDur"))
        self.gridLayout_2.addWidget(self.label_StepDur, 9, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 24, 0, 1, 1)
        self.lineEdit_weight = QtGui.QLineEdit(self.tab)
        self.lineEdit_weight.setObjectName(_fromUtf8("lineEdit_weight"))
        self.gridLayout_2.addWidget(self.lineEdit_weight, 14, 1, 1, 1)
        self.label_AcqTime = QtGui.QLabel(self.tab)
        self.label_AcqTime.setObjectName(_fromUtf8("label_AcqTime"))
        self.gridLayout_2.addWidget(self.label_AcqTime, 5, 0, 1, 2)
        self.label_InjTime = QtGui.QLabel(self.tab)
        self.label_InjTime.setObjectName(_fromUtf8("label_InjTime"))
        self.gridLayout_2.addWidget(self.label_InjTime, 17, 0, 1, 1)
        self.pushButton_clear = QtGui.QPushButton(self.tab)
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.gridLayout_2.addWidget(self.pushButton_clear, 25, 1, 1, 1)
        self.label_patient = QtGui.QLabel(self.tab)
        self.label_patient.setObjectName(_fromUtf8("label_patient"))
        self.gridLayout_2.addWidget(self.label_patient, 3, 0, 1, 2)
        self.label_height = QtGui.QLabel(self.tab)
        self.label_height.setObjectName(_fromUtf8("label_height"))
        self.gridLayout_2.addWidget(self.label_height, 13, 0, 1, 1)
        self.lineEdit_InjTime = QtGui.QLineEdit(self.tab)
        self.lineEdit_InjTime.setObjectName(_fromUtf8("lineEdit_InjTime"))
        self.gridLayout_2.addWidget(self.lineEdit_InjTime, 17, 1, 1, 1)
        self.label_TomoSteps = QtGui.QLabel(self.tab)
        self.label_TomoSteps.setObjectName(_fromUtf8("label_TomoSteps"))
        self.gridLayout_2.addWidget(self.label_TomoSteps, 8, 0, 1, 2)
        self.label_InjDate = QtGui.QLabel(self.tab)
        self.label_InjDate.setObjectName(_fromUtf8("label_InjDate"))
        self.gridLayout_2.addWidget(self.label_InjDate, 16, 0, 1, 1)
        self.label_AcqDate = QtGui.QLabel(self.tab)
        self.label_AcqDate.setObjectName(_fromUtf8("label_AcqDate"))
        self.gridLayout_2.addWidget(self.label_AcqDate, 4, 0, 1, 2)
        self.label_AcqDur = QtGui.QLabel(self.tab)
        self.label_AcqDur.setObjectName(_fromUtf8("label_AcqDur"))
        self.gridLayout_2.addWidget(self.label_AcqDur, 10, 0, 1, 2)
        self.pushButton_reload = QtGui.QPushButton(self.tab)
        self.pushButton_reload.setObjectName(_fromUtf8("pushButton_reload"))
        self.gridLayout_2.addWidget(self.pushButton_reload, 25, 0, 1, 1)
        self.label_camera = QtGui.QLabel(self.tab)
        self.label_camera.setObjectName(_fromUtf8("label_camera"))
        self.gridLayout_2.addWidget(self.label_camera, 11, 0, 1, 2)
        self.label_activity = QtGui.QLabel(self.tab)
        self.label_activity.setObjectName(_fromUtf8("label_activity"))
        self.gridLayout_2.addWidget(self.label_activity, 15, 0, 1, 1)
        self.lineEdit_activity = QtGui.QLineEdit(self.tab)
        self.lineEdit_activity.setObjectName(_fromUtf8("lineEdit_activity"))
        self.gridLayout_2.addWidget(self.lineEdit_activity, 15, 1, 1, 1)
        self.pushButton_confirm = QtGui.QPushButton(self.tab)
        self.pushButton_confirm.setObjectName(_fromUtf8("pushButton_confirm"))
        self.gridLayout_2.addWidget(self.pushButton_confirm, 23, 0, 1, 2)
        self.label_description = QtGui.QLabel(self.tab)
        self.label_description.setObjectName(_fromUtf8("label_description"))
        self.gridLayout_2.addWidget(self.label_description, 20, 0, 1, 1)
        self.lineEdit_description = QtGui.QLineEdit(self.tab)
        self.lineEdit_description.setObjectName(_fromUtf8("lineEdit_description"))
        self.gridLayout_2.addWidget(self.lineEdit_description, 20, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_default_settings = QtGui.QPushButton(self.tab_2)
        self.pushButton_default_settings.setObjectName(_fromUtf8("pushButton_default_settings"))
        self.gridLayout_3.addWidget(self.pushButton_default_settings, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_ip = QtGui.QLabel(self.groupBox)
        self.label_ip.setObjectName(_fromUtf8("label_ip"))
        self.gridLayout_4.addWidget(self.label_ip, 2, 0, 1, 1)
        self.lineEdit_to_ae = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_to_ae.setObjectName(_fromUtf8("lineEdit_to_ae"))
        self.gridLayout_4.addWidget(self.lineEdit_to_ae, 1, 2, 1, 1)
        self.lineEdit_ip = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ip.setObjectName(_fromUtf8("lineEdit_ip"))
        self.gridLayout_4.addWidget(self.lineEdit_ip, 2, 2, 1, 1)
        self.label_to_ae = QtGui.QLabel(self.groupBox)
        self.label_to_ae.setObjectName(_fromUtf8("label_to_ae"))
        self.gridLayout_4.addWidget(self.label_to_ae, 1, 0, 1, 1)
        self.lineEdit_from_ae = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_from_ae.setObjectName(_fromUtf8("lineEdit_from_ae"))
        self.gridLayout_4.addWidget(self.lineEdit_from_ae, 0, 2, 1, 1)
        self.label_from_ae = QtGui.QLabel(self.groupBox)
        self.label_from_ae.setObjectName(_fromUtf8("label_from_ae"))
        self.gridLayout_4.addWidget(self.label_from_ae, 0, 0, 1, 1)
        self.label_port = QtGui.QLabel(self.groupBox)
        self.label_port.setObjectName(_fromUtf8("label_port"))
        self.gridLayout_4.addWidget(self.label_port, 3, 0, 1, 1)
        self.lineEdit_port = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_port.setObjectName(_fromUtf8("lineEdit_port"))
        self.gridLayout_4.addWidget(self.lineEdit_port, 3, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)
        self.pushButton_save_settings = QtGui.QPushButton(self.tab_2)
        self.pushButton_save_settings.setObjectName(_fromUtf8("pushButton_save_settings"))
        self.gridLayout_3.addWidget(self.pushButton_save_settings, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.checkBox_delete_in = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_delete_in.setObjectName(_fromUtf8("checkBox_delete_in"))
        self.gridLayout_5.addWidget(self.checkBox_delete_in, 1, 0, 1, 1)
        self.checkBox_delete_temp = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_delete_temp.setObjectName(_fromUtf8("checkBox_delete_temp"))
        self.gridLayout_5.addWidget(self.checkBox_delete_temp, 2, 0, 1, 1)
        self.checkBox_save_local = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_save_local.setObjectName(_fromUtf8("checkBox_save_local"))
        self.gridLayout_5.addWidget(self.checkBox_save_local, 3, 0, 1, 1)
        self.label_output_dir = QtGui.QLabel(self.groupBox_2)
        self.label_output_dir.setObjectName(_fromUtf8("label_output_dir"))
        self.gridLayout_5.addWidget(self.label_output_dir, 5, 0, 1, 1)
        self.lineEdit_output_dir = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_output_dir.setObjectName(_fromUtf8("lineEdit_output_dir"))
        self.gridLayout_5.addWidget(self.lineEdit_output_dir, 5, 1, 1, 1)
        self.checkBox_transfer = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_transfer.setObjectName(_fromUtf8("checkBox_transfer"))
        self.gridLayout_5.addWidget(self.checkBox_transfer, 0, 0, 1, 1)
        self.label_input_dir = QtGui.QLabel(self.groupBox_2)
        self.label_input_dir.setObjectName(_fromUtf8("label_input_dir"))
        self.gridLayout_5.addWidget(self.label_input_dir, 4, 0, 1, 1)
        self.label_input_dir_path = QtGui.QLabel(self.groupBox_2)
        self.label_input_dir_path.setText(_fromUtf8(""))
        self.label_input_dir_path.setObjectName(_fromUtf8("label_input_dir_path"))
        self.gridLayout_5.addWidget(self.label_input_dir_path, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Config = QtGui.QAction(MainWindow)
        self.actionSave_Config.setObjectName(_fromUtf8("actionSave_Config"))
        self.actionLoad_Config = QtGui.QAction(MainWindow)
        self.actionLoad_Config.setObjectName(_fromUtf8("actionLoad_Config"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_height, self.lineEdit_weight)
        MainWindow.setTabOrder(self.lineEdit_weight, self.lineEdit_activity)
        MainWindow.setTabOrder(self.lineEdit_activity, self.lineEdit_InjDate)
        MainWindow.setTabOrder(self.lineEdit_InjDate, self.lineEdit_InjTime)
        MainWindow.setTabOrder(self.lineEdit_InjTime, self.pushButton_process)
        MainWindow.setTabOrder(self.pushButton_process, self.lineEdit_description)
        MainWindow.setTabOrder(self.lineEdit_description, self.pushButton_confirm)
        MainWindow.setTabOrder(self.pushButton_confirm, self.pushButton_reload)
        MainWindow.setTabOrder(self.pushButton_reload, self.pushButton_clear)
        MainWindow.setTabOrder(self.pushButton_clear, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.lineEdit_from_ae)
        MainWindow.setTabOrder(self.lineEdit_from_ae, self.lineEdit_to_ae)
        MainWindow.setTabOrder(self.lineEdit_to_ae, self.lineEdit_ip)
        MainWindow.setTabOrder(self.lineEdit_ip, self.lineEdit_port)
        MainWindow.setTabOrder(self.lineEdit_port, self.checkBox_transfer)
        MainWindow.setTabOrder(self.checkBox_transfer, self.checkBox_delete_in)
        MainWindow.setTabOrder(self.checkBox_delete_in, self.checkBox_delete_temp)
        MainWindow.setTabOrder(self.checkBox_delete_temp, self.checkBox_save_local)
        MainWindow.setTabOrder(self.checkBox_save_local, self.lineEdit_output_dir)
        MainWindow.setTabOrder(self.lineEdit_output_dir, self.pushButton_save_settings)
        MainWindow.setTabOrder(self.pushButton_save_settings, self.pushButton_default_settings)
        MainWindow.setTabOrder(self.pushButton_default_settings, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qSPECT", None))
        self.pushButton_process.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Performs initial processing steps. Need to confirm calculated post-injection time and % injected dose before saving...</p></body></html>", None))
        self.pushButton_process.setText(_translate("MainWindow", "Process...", None))
        self.lineEdit_InjDate.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter date in format day/month/year</p></body></html>", None))
        self.label_weight.setText(_translate("MainWindow", "Patient Weight (kg):", None))
        self.label_n_tomos.setText(_translate("MainWindow", "# of Tomos: ", None))
        self.label_n_slices.setText(_translate("MainWindow", "Axial Slices:", None))
        self.label_StepDur.setText(_translate("MainWindow", "Step Duration (s):", None))
        self.label_AcqTime.setText(_translate("MainWindow", "Acquisition Time:", None))
        self.label_InjTime.setText(_translate("MainWindow", "Injection Time (HHMM)", None))
        self.pushButton_clear.setToolTip(_translate("MainWindow", "<html><head/><body><p>&quot;Clear the buffer&quot;</p></body></html>", None))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear Input Directory", None))
        self.label_patient.setText(_translate("MainWindow", "Patient:", None))
        self.label_height.setText(_translate("MainWindow", "Patient Height (m):", None))
        self.lineEdit_InjTime.setToolTip(_translate("MainWindow", "<html><head/><body><p>Injection time in 24h format HH:MM or HHMM</p></body></html>", None))
        self.label_TomoSteps.setText(_translate("MainWindow", "Tomo Steps:", None))
        self.label_InjDate.setText(_translate("MainWindow", "Injection Date (D/M/Y):", None))
        self.label_AcqDate.setText(_translate("MainWindow", "Acquisition Date:", None))
        self.label_AcqDur.setText(_translate("MainWindow", "Time Per Bed Position (m):", None))
        self.pushButton_reload.setToolTip(_translate("MainWindow", "<html><head/><body><p>Reload TOMO &amp; IRACS images from input directory</p></body></html>", None))
        self.pushButton_reload.setText(_translate("MainWindow", "Reload Images", None))
        self.label_camera.setText(_translate("MainWindow", "Camera:", None))
        self.label_activity.setText(_translate("MainWindow", "Activity (MBq):", None))
        self.lineEdit_activity.setToolTip(_translate("MainWindow", "<html><head/><body><p>Activity of Lu-177 at time of injection (in MBq)</p></body></html>", None))
        self.pushButton_confirm.setToolTip(_translate("MainWindow", "<html><head/><body><p>Write output images and transfer to \'Patient Browser\'</p></body></html>", None))
        self.pushButton_confirm.setText(_translate("MainWindow", "Confirm and Transfer...", None))
        self.label_description.setText(_translate("MainWindow", "Series Description:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "qSPECT", None))
        self.pushButton_default_settings.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load Default configuration settings</p></body></html>", None))
        self.pushButton_default_settings.setText(_translate("MainWindow", "Load Default Settings", None))
        self.groupBox.setTitle(_translate("MainWindow", "Dicom Details:", None))
        self.label_ip.setText(_translate("MainWindow", "IP Address:", None))
        self.lineEdit_to_ae.setToolTip(_translate("MainWindow", "Database AE Title", None))
        self.lineEdit_ip.setToolTip(_translate("MainWindow", "IP address of image database (127.0.0.1)", None))
        self.label_to_ae.setText(_translate("MainWindow", "Transfer AE Title (To):", None))
        self.lineEdit_from_ae.setToolTip(_translate("MainWindow", "Local AE Title (QSPECT)", None))
        self.label_from_ae.setText(_translate("MainWindow", "qSPECT AE Title (From):", None))
        self.label_port.setText(_translate("MainWindow", "Port:", None))
        self.lineEdit_port.setToolTip(_translate("MainWindow", "port # (104)", None))
        self.pushButton_save_settings.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save configuration settings. Will load next time qSPECT is opened</p></body></html>", None))
        self.pushButton_save_settings.setText(_translate("MainWindow", "Save Current Settings", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output Files:", None))
        self.checkBox_delete_in.setToolTip(_translate("MainWindow", "Select whether to clear qSPECT input files after processing and transfer completes", None))
        self.checkBox_delete_in.setText(_translate("MainWindow", "Delete Input Directory When Complete", None))
        self.checkBox_delete_temp.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select whether to delete temp/ files after processing and transfer completes</p></body></html>", None))
        self.checkBox_delete_temp.setText(_translate("MainWindow", "Delete Temp Files When Complete", None))
        self.checkBox_save_local.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select whether to create backup copy of output files on local folder (in case or transfer errors)</p></body></html>", None))
        self.checkBox_save_local.setText(_translate("MainWindow", "Save Local Copy", None))
        self.label_output_dir.setText(_translate("MainWindow", "Backup Directory:", None))
        self.lineEdit_output_dir.setToolTip(_translate("MainWindow", "<html><head/><body><p>Parent directory for backup of qSPECTed images (..\\qspected_images\\PATIENT_DATE)</p></body></html>", None))
        self.checkBox_transfer.setText(_translate("MainWindow", "Transfer to DICOM Database", None))
        self.label_input_dir.setText(_translate("MainWindow", "Input Directory (modifiable in text file):", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Config", None))
        self.actionSave_Config.setText(_translate("MainWindow", "Save Config...", None))
        self.actionLoad_Config.setText(_translate("MainWindow", "Load Config...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

